export const data = [
  {
    name: 'Naruto1 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto2 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto3 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto4 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto5 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto6 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto7 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto8 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto9 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto10 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto11 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto12 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto13 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto14 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto15 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
  {
    name: 'Naruto16 Uzumaki',
    gender: 'Male',
    birthPlace: 'Konoha Village',
    religion: 'Catholic',
    nationality: 'Japanese',
    marital: 'Single',
  },
];
